Refactor into DTO / Model schema approach
SprocketBot/sprocket-common pull request #4
Opened 2021-12-13 03:55 UTC by 0c370t

By splitting referential schemas away from the DTO schemas, we can avoid circular schemas.

This enables us to more easily compose and mutate schemas when typing endpoints (i.e. update franchise is just franchise.omit({id: true}).optional(), instead of an entirely new schema)

2021-12-13 15:36 UTC, zachstence requested changes
Mostly formatting changes needed to keep it pretty :)

Also:
- In order to preserve consistency between the Schemas and DTO Schemas, I bet we could have a unit test that validates that every pair of schemas has the same keys (even though they will have different values). This way we know that we didn't accidentally add an extra key to a DTO and not the base schema. Could also validate that the same keys are optional/required in both schemas.
- How are we going to translate to/from DTO? I think we could probably write a function to do so with a configurable "population" (to translate IDs to objects) like we had when fetching things with MikroORM

2021-12-13 15:36 UTC, zachstence commented on src/sprocket-common/core/models/authorization/action.model.ts
> +export type ActionModel = z.infer<typeof ActionSchema>;
`Action` should have a DTO, even if it is identical to `ActionSchema`. This way our naming/schema use is consistent

2021-12-13 15:36 UTC, zachstence commented on src/sprocket-common/core/models/authorization/franchise_leadership_role.model.ts
> +    bearer: z.number(),
It would be nice if Zod had a different function (or we could add one) like `z.id()` that would type it as a number, but also somehow tell you that this is a key field in the database. I wonder if we could extend Zod with that function and provide some useful JSDoc or type hints?

2021-12-13 15:36 UTC, zachstence commented on src/sprocket-common/core/models/configuration/organization_configuration_key.model.ts
> +export type OrganizationConfigurationKeyModel = z.infer<typeof OrganizationConfigurationKeySchema>;
Add blank lines between schemas/types so formatting is consistent across files

2021-12-13 15:36 UTC, zachstence commented on src/sprocket-common/core/models/franchise/game_skill_group.model.ts
> +    players: z.number().array(),
We should be consistent with `z.array(z.number())` or `z.number().array()` (similar for other datatypes and Zod modifiers). I think I prefer the former.

2021-12-13 15:36 UTC, zachstence commented on src/sprocket-common/core/models/franchise/team.model.ts
> +export type TeamDto = z.infer<typeof TeamSchema>;
Consistent ordering of the types/schemas (DTO first or Model first)

2021-12-13 15:37 UTC, zachstence commented
Also very excited for this new model, I think its a great idea and should make the code a lot simpler to write

2021-12-14 00:46 UTC, 0c370t commented on src/sprocket-common/core/models/franchise/game_skill_group.model.ts
> +    players: z.number().array(),
I made them all `z.number().array()` as part of this refactor; it remains easier to read as you chain things (i.e. number.min().max().optional().array()`

2021-12-14 01:50 UTC, zachstence approved these changes

2021-12-14 01:50 UTC, merged