Matchmaking MVP module
SprocketBot/sprocket-common pull request #9
Opened 2022-01-29 05:29 UTC by 0c370t

2022-01-30 01:31 UTC, zachstence requested changes
Delete empty files:
`src/sprocket-common/core/index.ts`
`src/sprocket-common/core/types/index.ts`

2022-01-30 01:31 UTC, zachstence commented on src/global.module.ts
> +            urls: [config.get("transport.url")] as string[],
Add `config.has` checks above

2022-01-30 01:31 UTC, zachstence commented on src/global.types.ts
> +    Matchmaking = "CommonMatchmakingClient",
Change this value to `CommonClientMatchmaking` to match the others above

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/events/events.service.ts
> +                payload: value as EventPayload<T>,
Can we do any type checking with Zod here?

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/matchmaking.types.ts
> +    CheckInToScrim = "CheckIntoScrim",
"CheckIntoScrim" -> "CheckInToScrim"

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/schemas/CreateScrim.schema.ts
> +    author: ScrimPlayerSchema,
Should `author` be optional here? We're checking for the author in the Matchmaking Service
https://github.com/SprocketBot/matchmaking-service/pull/1/files#diff-7bbaec22f17d7bfac07e56821a33c5f94d58a11a44e97f4be6ee22940bb03174R21

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/schemas/GetAllScrims.schema.ts
> +export const GetAllScrims_Request = z.object({});
Use `z.void()` here to signify no data is necessary for the request

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/schemas/JoinScrim.schema.ts
> +    id: z.string(),
`.uuid()`

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/schemas/LeaveScrim.schema.ts
> +    id: z.string(),
`.uuid()`

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/schemas/QueueStatus.schema.ts
> +export const GetQueueStatus_Request = z.object({});
Not implemented in the Matchmaking Service

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/types/Scrim.ts
> +     * Scrim has filled, and players are confirming
"checking in" instead of "confirming"

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/types/Scrim.ts
> +     * Replays are submitted, this scrim is being removed
Will not always be replays

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/types/Scrim.ts
> +
Remove line break

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/types/ScrimPlayer.ts
> +    ,
Weird comma

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/types/ScrimSettings.ts
> +    teamSize: z.number(),
Teams should have a minimum size of 1
`.min(1)`

2022-01-30 01:31 UTC, zachstence commented on src/sprocket-common/matchmaking/types/ScrimSettings.ts
> +    teamCount: z.number(),
Need at least 2 teams for a scrim
`.min(2)`

2022-01-30 02:22 UTC, 0c370t commented on src/sprocket-common/events/events.service.ts
> +                payload: value as EventPayload<T>,
I'm not sure why this is showing as part of this pr, but value is parsed on line 20

2022-01-30 02:23 UTC, 0c370t commented on src/sprocket-common/matchmaking/schemas/CreateScrim.schema.ts
> +    author: ScrimPlayerSchema,
For now, yes, there will be another set of endpoints for moderator / admin commands that may create scrims without authors

2022-01-30 02:24 UTC, 0c370t commented on src/sprocket-common/matchmaking/schemas/GetAllScrims.schema.ts
> +export const GetAllScrims_Request = z.object({});
Breaks the signature for the matchmaking service; leaving as is for now.

2022-01-30 02:25 UTC, 0c370t commented on src/sprocket-common/matchmaking/schemas/QueueStatus.schema.ts
> +export const GetQueueStatus_Request = z.object({});
This will also be included in the mod/admin commands

2022-01-30 02:26 UTC, 0c370t commented on src/sprocket-common/matchmaking/types/Scrim.ts
> +
Was intentional to separate primitives from non-primitives

2022-01-31 14:24 UTC, zachstence approved these changes

2022-01-31 14:32 UTC, zachstence commented
Ready to merge when [SprocketBot/matchmaking-service#1](https://github.com/SprocketBot/matchmaking-service/pull/1) is

2022-02-01 01:47 UTC, zachstence approved these changes

2022-02-01 01:50 UTC, merged